In [1]:
import csv,os,re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import nltk

In [3]:
os.chdir(os.path.join(os.getcwd(), ('Data/')))

In [16]:
data_df = pd.read_csv('dataset.csv',names=['Author','Text'])

In [17]:
len(data_df['Author'].value_counts())

50

In [18]:
data_df['Text'] = data_df['Text'].map(lambda x: re.sub('\r|\n|\'','',x))
data_df['Text'] = data_df['Text'].map(lambda x: re.sub(r'--\d\d\d-\d\d\d-\d\d\d\d','',x))

In [19]:
#data_df.head()
#Generate corpus of words for use by the CountVectorizer
corpus = []
for text in data_df['Text']:
    corpus.append(text)
#corpus[11]

In [20]:
# split the dataset based on attribute 'Author'.
from sklearn.model_selection import train_test_split
y = data_df.pop("Author")
#X = data_df
#print(y)
X_train, X_test, y_train, y_test = train_test_split(data_df['Text'], y, test_size=0.3, stratify=y,random_state=42) 
#print((X_train['Text']))

In [21]:
# Both test and train labels contain instances of all the 50 authors. 
df_ytrain = pd.DataFrame(y_train)
df_ytest = pd.DataFrame(y_test)
print(len(df_ytrain['Author'].value_counts()))
print(len(df_ytest['Author'].value_counts()))
type(df_ytrain)

50
50


pandas.core.frame.DataFrame

In [22]:
#stop words removal
from nltk.corpus import stopwords
stop = stopwords.words('english')

#remove punctuations
X_train = X_train.str.replace("[^\w\s]", "")
X_test = X_test.str.replace("[^\w\s]", "")

#remove stop words
X_train = X_train.apply((lambda x: ' '.join([word for word in x.split() if word not in (stop)])))
X_test = X_test.apply((lambda x: ' '.join([word for word in x.split() if word not in (stop)])))
#print((X_train.head(1)))
#print(X_test.head(1))
#i=1
#for row in X_train:
#    print(row)
#    if i == 1:
#        break'''

In [38]:
from sklearn import preprocessing, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# label encode the target variable 
encoder = preprocessing.LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word',max_df=0.50,min_df=0.01)
#count_vect.fit(corpus)

# transform the training and validation data using count vectorizer object
Xtrain_count =  count_vect.fit_transform(X_train)
Xtest_count =  count_vect.transform(X_test)

#print(count_vect.get_feature_names())

print(Xtrain_count.__str__)
print(Xtrain_count)

<bound method spmatrix.__str__ of <3500x3561 sparse matrix of type '<class 'numpy.int64'>'
	with 520017 stored elements in Compressed Sparse Row format>>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  (0, 2025)	1
  (0, 3056)	1
  (0, 3270)	1
  (0, 3046)	1
  (0, 318)	1
  (0, 2021)	1
  (0, 2113)	1
  (0, 2961)	1
  (0, 2374)	1
  (0, 3476)	1
  (0, 2816)	1
  (0, 112)	1
  (0, 1821)	1
  (0, 3240)	1
  (0, 1176)	1
  (0, 3481)	1
  (0, 158)	1
  (0, 1954)	1
  (0, 1286)	1
  (0, 775)	1
  (0, 696)	1
  (0, 1982)	1
  (0, 2660)	1
  (0, 2188)	1
  (0, 1907)	1
  :	:
  (3499, 839)	1
  (3499, 1670)	1
  (3499, 48)	1
  (3499, 2868)	1
  (3499, 1542)	1
  (3499, 1171)	1
  (3499, 998)	1
  (3499, 2314)	1
  (3499, 3226)	1
  (3499, 1930)	1
  (3499, 347)	2
  (3499, 915)	1
  (3499, 2741)	1
  (3499, 1202)	1
  (3499, 357)	1
  (3499, 78)	1
  (3499, 1369)	1
  (3499, 1989)	1
  (3499, 647)	1
  (3499, 3495)	1
  (3499, 3046)	1
  (3499, 2374)	1
  (3499, 16

In [31]:
# word level tf-idf
tfidf_vect = TfidfVectorizer(analyzer='word',sublinear_tf=True, max_df=0.50,min_df=0.01)
#tfidf_vect.fit(corpus)
Xtrain_tfidf = tfidf_vect.fit_transform(X_train)
Xtest_tfidf = tfidf_vect.transform(X_test)

#print(Xtrain_tfidf.__str__)
#print(Xtrain_tfidf)

# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', ngram_range=(2,3),sublinear_tf=True, max_df=0.50,min_df=0.01)
#tfidf_vect_ngram.fit(corpus)
Xtrain_tfidf_ngram = tfidf_vect_ngram.fit_transform(X_train)
Xtest_tfidf_ngram = tfidf_vect_ngram.transform(X_test)

print(Xtrain_tfidf_ngram.__str__)
print(Xtrain_tfidf_ngram)

<bound method spmatrix.__str__ of <3500x886 sparse matrix of type '<class 'numpy.float64'>'
	with 63980 stored elements in Compressed Sparse Row format>>
  (0, 334)	0.15120287306396993
  (0, 493)	0.15819676836011215
  (0, 813)	0.16815733131096924
  (0, 133)	0.28108830006372765
  (0, 838)	0.1799954814808407
  (0, 304)	0.1377453624650417
  (0, 144)	0.28197329585488445
  (0, 170)	0.18420240924838607
  (0, 808)	0.16601527811112568
  (0, 309)	0.15659692589985375
  (0, 492)	0.15544570165165714
  (0, 97)	0.16653797088191252
  (0, 527)	0.16653797088191252
  (0, 237)	0.17556353383454715
  (0, 246)	0.1692825341505534
  (0, 651)	0.14326982924075973
  (0, 15)	0.16601527811112568
  (0, 147)	0.18079528656714403
  (0, 134)	0.16601527811112568
  (0, 775)	0.13708810722557516
  (0, 21)	0.1742086393863196
  (0, 302)	0.14051282349587751
  (0, 411)	0.10310118762872844
  (0, 539)	0.12869873298997017
  (0, 410)	0.17487917340371287
  :	:
  (3498, 749)	0.14912587653345552
  (3498, 26)	0.15549231665033894
  (34

In [32]:
def train_model(classifier, feature_vector_train, label, feature_vector_test, is_neural_net=False):
    # fit the training dataset on the classifier
    classifier.fit(feature_vector_train, label)
    
    # predict the labels on validation dataset
    predictions = classifier.predict(feature_vector_test)
    
    if is_neural_net:
        predictions = predictions.argmax(axis=-1)
    
    return metrics.accuracy_score(predictions, y_test)

In [33]:
print(Xtrain_tfidf.shape)
# Naive Bayes on Count Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), Xtrain_count, y_train, Xtest_count)
print ("NB, Count Vectors: ", accuracy)


(3500, 3561)
NB, Count Vectors:  0.788


In [34]:
# Naive Bayes on Word Level TF IDF Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), Xtrain_tfidf, y_train, Xtest_tfidf)
print ("NB, WordLevel TF-IDF: ", accuracy)

# Naive Bayes on Ngram Level TF IDF Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), Xtrain_tfidf_ngram, y_train, Xtest_tfidf_ngram)
print ("NB, N-Gram Vectors: ", accuracy)

NB, WordLevel TF-IDF:  0.7553333333333333
NB, N-Gram Vectors:  0.6593333333333333


In [39]:
# SVM on Ngram Level TF IDF Vectors

accuracy = train_model(svm.SVC(), Xtrain_tfidf_ngram, y_train, Xtest_tfidf_ngram)
print ("SVM, N-Gram Vectors: ", accuracy)

SVM, N-Gram Vectors:  0.5553333333333333
